#!/bin/bash

SuiteFileName=${1}
ProgramName=${2}

IncorrectArgumentNumber () 
{
	echo "Incorrect number of arguments" >&2
	exit 1
}

if [ ${#} -ne 2 ]; then 
	IncorrectArgumentNumber
fi 

if [ ! -r ${1} ]; then
	echo "$SuiteFileName is not readable" >&2
	exit 1
fi 

if [ ! -x ${2} ]; then
	echo "$ProgramName is not executable" >&2
	exit 1
fi

err=0
for Filename in $(cat ${1}); do 
	
	if [ ! -r ${Filename}.in -a -e ${Filename}.in ]
	then 
		echo ${Filename}.in is not readable >&2
		err=1
	elif [ ! -r ${Filename}.args -a -e ${Filename}.args ]
	then
		echo ${Filename}.args is not readable >&2
		err=1
	elif [ ! -w ${Filename}.out -a -e ${Filename}.out ]
	then
		echo ${Filename}.out is not writeable >&2
		err=1
	elif [ -e ${Filename}.in -a -e ${Filename}.args ]
	then
		cat ${Filename}.in | ${2} $(cat ${Filename}.args) > ${Filename}.out
	elif [ -e ${Filename}.in ]
	then
		cat ${Filename}.in | ${2} > ${Filename}.out
	elif [ -e ${Filename}.args ] 
	then
		${2} $(cat ${Filename}.args) > ${Filename}.out
	else 
		touch ${Filename}.out
	fi

done

if [ $err -eq 1 ]; then
	exit 1
fi
